### PR TITLE
base: clang-layer: fix building llvm with GCC13

### PR DESCRIPTION
**Pull request by MrCry0**
Clang 14.0.3 fails to build with GCC 13.1.x with the error [1]. Apply an upstream fix for this issue.

[1]
| In file included from llvm/lib/Support/Signals.cpp:14: | llvm/include/llvm/Support/Signals.h:119:8: error: variable or field 'CleanupOnSignal' declared void
|   119 |   void CleanupOnSignal(uintptr_t Context);
|       |        ^~~~~~~~~~~~~~~
| llvm/include/llvm/Support/Signals.h:119:24: error: 'uintptr_t' was not declared in this scope

Upstream-Status: Pending [meta-clang]

### CODE REVIEW

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Comment by quaresmajose** [comment]
Submitted https://github.com/kraj/meta-clang/pull/816
